### ISSUE TITLE
Swipe actions might be inverted

### ISSUE THREAD

**Issue by camflan** [Kinark/winston#12]
I think the swipe actions are inverted - “Swipe left” action happens on “swipe right” and vice versa

https://github.com/Kinark/winston/assets/27292/7a32c299-1476-4b5a-9265-47bd981dcec8

**Comment by itsamoreh** [comment]
This confused me as well! I agree they're inverted.

**Comment by ojsef39** [comment]
for reference discord bug report: https://discord.com/channels/1094807340903039048/1140666942299066519

**Comment by ojsef39** [comment]
Is fixed :)
