### ISSUE TITLE
Feature Request: Can we get a "Drag Right to go Back" option?

### ISSUE THREAD

**Issue by itsamoreh** [Kinark/winston#13]
I have an iPhone 12 Pro with a case on and I need to use two hands to go back. One of my favourite features of Apollo was "Swipe right to go back" which disabled the swipe right options on posts and comments. This allowed me to use one hand to navigate almost anywhere in the app.

Having this same feature in winston would be fantastic.

Related: Currently the swipe options are reversed (see #12). I used the direction that it should be "Drag right to go back", not the direction it currently is in Winston's settings.

**Comment by ojsef39** [comment]
Hi @itsamoreh, Kinark implemented "swipe anywhere to go back" and swiping on the bottom bar to go back, is that what you were looking for?

**Comment by itsamoreh** [comment]
Yes this has been implemented! Thanks!
