### ISSUE TITLE
"Report a bug" doesn't

### ISSUE THREAD

**Issue by maurymarkowitz** [Kinark/winston#21]
Pressing "report a bug" in the app doesn't appear to do anything. I can see the link/button reacting to the tap, but nothing happens in response.

**Comment by maurymarkowitz** [comment]
It appears that the button does do something, but the resulting email does not become visible on the display. It appears to remain in the Mail app itself, where you'll see it as a sort of floating tab at the bottom of the screen.

**Comment by ojsef39** [comment]
Hi @maurymarkowitz is this still hapenning to you? It works as intended for me on the latest build :)

**Comment by zburk** [comment]
This works for me as expected in 1.0 (114)

**Comment by ojsef39** [comment]
i was able to reproduce this in older versions but now it's gone for me too @zburk 

can you confirm? @maurymarkowitz if yes i will close this 😀

**Comment by josemsanchezb** [comment]
Hi, the problem @maurymarkowitz is facing is that 'Report a bug' button opens the stock iOS Mail app instead of the Default Mail app set in the OS Settings. So if anyone has uninstalled the stock iOS Mail app the 'Report a bug' does nothing

**Comment by maurymarkowitz** [comment]
@josemsanchezb  - I have Mail installed, and know of no way to uninstall it. Yes, it is my default mail app.

**Comment by maurymarkowitz** [comment]
Yes, this is working properly now, you can close it.
