### ISSUE TITLE
Clicking on blank save in flat view no longer open comments

### ISSUE THREAD

**Issue by Wibbbs** [Kinark/winston#43]
Previously to this newest version tapping on the blank space either above or below the media would open the comments, it now appears to not do anything.

The only way to open the comments now appears to be to tap on the post title.  Image below of area I am talking about.

![IMG_6518](https://github.com/Kinark/winston/assets/24574428/9ec75ade-ddbc-4830-b214-0241273e05ed)

**Comment by ojsef39** [comment]
Fixed with Build 124 (Commit: https://github.com/Kinark/winston/commit/885093691de95c657cfcbb3f1b6d3fa618cb322e)
