### ISSUE TITLE
Tap to vote

### ISSUE THREAD

**Issue by arunsathiya** [Kinark/winston#68]
Feature request. It’d be nice to tap on the upvote and downvote buttons on comments. Right now, it seems that the only way to vote is to swipe.

**Comment by ojsef39** [comment]
thank you for your feature request! we'll look into that.

btw you can also long press the comment to up/downvote :)

**Comment by ojsef39** [comment]
The issue is currently resolved and merged to the alpha branch for testing. thx @ben-wheeler

**Comment by ben-wheeler** [comment]
just thought i would comment to note this got added into the latest test flight build published today 🎉
