### ISSUE TITLE
Can't open comment threads in inbox

### ISSUE THREAD

**Issue by Im-Mefju** [Kinark/winston#74]
Im not sure when it started to happen but i think it was after update to ios 17.

**Comment by ojsef39** [comment]
hi, thanks for your report! 
Could you please provide a screen recording? Thank you :)

**Comment by Im-Mefju** [comment]
> hi, thanks for your report! 
> Could you please provide a screen recording? Thank you :)

I would but screen recording doesn't show touching the screen so you only see inbox with no animation or anything.

**Comment by ojsef39** [comment]
> I would but screen recording doesn't show touching the screen so you only see inbox with no animation or anything.

ah yeah, that's true, unfortunately. but I see what you mean, I can replicate this bug.

**Comment by Im-Mefju** [comment]
Issue was fixed in latest update
