### ISSUE TITLE
Does this work on older versions of ios 16?

### ISSUE THREAD

**Issue by Shadowspear123** [Kinark/winston#80]
HI. I would love to try this app but unfortunately testflight won't let me install it because I'm on an older version of ios 16 (16.1). Would the IPA work if I sideloaded it?

**Comment by ojsef39** [comment]
Ahh, my bad, I think the minimum requirement is 16.4.
So neither TestFlight install nor sideloading wouldn't work.

Hope this answers your question, feel free to reopen this if you got another question :)

**Comment by Shadowspear123** [comment]
I agree! I would love to use this app but unfortunately can’t because of the ios version restriction. Would it be possible to expand support down to iOS 16.1?

**Comment by ojsef39** [comment]
Hi @Void48 @Shadowspear123, I'm sorry to inform you guys that we won't support older versions of iOS (and have not planned to change that in the future)
