### ISSUE TITLE
Long pressing comments crushes the app

### ISSUE THREAD

**Issue by Im-Mefju** [Kinark/winston#85]
After latest update long pressing comments crushes the app with no logs or anything. I would record this but recording doesn't show anything usefull

**Comment by ojsef39** [comment]
hi @Im-Mefju, i can't replicate this bug. can you you please add more information like:
- what device are you using?
- have tried clearing the cache (settings->general) or reinstalling the app?

**Comment by Im-Mefju** [comment]
> hi @Im-Mefju, i can't replicate this bug. can you you please add more information like:
> - what device are you using?
> - have you tried clearing the cache (settings->general) or reinstalling the app?

Reinstalling the app worked
