### ISSUE TITLE
TestFlight link broken (again?)

### ISSUE THREAD

**Issue by Qhilm** [Kinark/winston#87]
A similar issue (#30) was opened in the past but it's lacking any details, so I'm not sure I am facing the same issue.

When I tap the link, TestFlight cross launches, then displays a popup stating:

>### beta not found
>There is a problem with the public link URL. Contact the developer for more information.

I am on iOS 17.0.2 on an iPhone 12 mini and I'm using the German App Store, in case that's relevant.

**Comment by ojsef39** [comment]
Hi @Qhilm,

yeah, unfortunately, TestFlight is down again :(

If you want to stay up to date in that regard, please consider joining our discord server, where we have a channel for announcements/updates on that topic :)

Link to the channel -> https://discord.gg/4Qg3gYYq
